<?php
/**
 * Created by PhpStorm.
 * User: lxwn
 * Date: 2018/5/9
 * Time: 下午3:47
 */

namespace Admin\Controller;

class EmptyController extends AdminBaseController
{
	public function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
	}
}