<?php
namespace Admin\Controller;

class IndexController extends AdminBaseController {

	public function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
	}

	public function index()
	{
		$this->display();
	}


}