<?php
/**
 * Created by PhpStorm.
 * User: lxwn
 * Date: 2018/5/9
 * Time: 下午3:53
 */

namespace Admin\Controller;

class LoginController extends AdminBaseController
{
	public function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub

	}

	public function index()
	{
		layout(false);
		$this->display();
	}

	public function code()
	{
		$Verify         =   new \Think\Verify();
		$Verify->entry();
	}



	public function ajaxLogin()
	{
		$data           =   I('post.');
		$filed_arr      =   ['password','account','code'];

		if (checkFieldBeEmpty($data,$filed_arr,$msg)) {
			$this->output($msg);
		}

		$verify = new \Think\Verify();

		if(!$verify->check($data['code'])){
			$this->output(50001);
		};

		$password       =   md5($data['password']);
		$account_info   =   M('admin_user')->where("account='{$data['account']}' and password='{$password}'")->find();

		if ($account_info) {
			$this->refreshCache($account_info['id']);
			session($this->user_id_field,$account_info['id']);
			$this->setCache($this->user_type_field,$account_info['type']);
			$jump_arr   =   $this->getCache('jump_info');
			$temp       =   explode('/',$jump_arr[0]);
			$uri        =   $temp[1] == "*" ?   $temp[0].'/'.'index'    :   $temp[0].'/'.$temp[1];
			$data       =   array('url'=>U($uri));
			$this->output(1,$data);
		} else{
			$this->output(70001);
		}
	}

	public function logout()
	{
		$this->delCache('admin_user_id');
		$this->delCache('jump_info');
		$this->delCache('menu_info');
		$this->newRedirect('login/index',[],1,1);
	}

}