<?php
/**
 * Created by PhpStorm.
 * User: lxwn
 * Date: 2018/5/22
 * Time: 上午11:48
 */

namespace Admin\Controller;

class UploadController extends AdminBaseController
{
	public function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
	}

	public function img()
	{

		$server_root        =   $_SERVER['DOCUMENT_ROOT'].'/';
		$project            =   "Public/upload/";
		$domain             =   $_SERVER['HTTP_HOST'].'/';
		$max_size           =   2048000;//2M
		$source             =   I('post.source');
		$file_type          =   I('post.file_type');

		$type = array(
			'image/gif',
			'image/jpeg',
			'image/jpg',
			'image/pjpeg',
			'image/png',
		);

		if (empty($_FILES['file']) || empty($source) || empty($type)) {
			$this->output(99999);
		}

		if($_FILES['file']['size'] > $max_size){
			$this->output(88888);
		}


		$name               =   rand(10000,99999).date('s').'_'.$_FILES['file']['name'];
		$year_p             =   date('Y').'/';
		$year               =   date('Y');
		$month_p            =   date('m').'/';
		$month              =   date('m');
		$day_p              =   date('d').'/';
		$day                =   date('d');

		if (!is_dir($server_root.$project.$year_p)) {
			$a=mkdir($server_root.$project.$year_p);
		}

		if (!is_dir($server_root.$project.$year_p.$month_p)) {
			mkdir($server_root.$project.$year_p.$month_p);
		}
		if (!is_dir($server_root.$project.$year_p.$month_p.$day_p)) {
			mkdir($server_root.$project.$year_p.$month_p.$day_p);
		}

		if(move_uploaded_file($_FILES['file']['tmp_name'],$server_root.$project.$year_p.$month_p.$day_p.$name)){
			$file_data          =   array(
				'domain'        =>  $_SERVER['HTTP_HOST'],
				'year'          =>  $year,
				'month'         =>  $month,
				'day'           =>  $day,
				'uri'           =>  $project.$year_p.$month_p.$day_p.$name,
				'create_time'   =>  date('Y-m-d H:i:s'),
				'source'        =>  $source,
				'type'          =>  $file_type,
				'name'          =>  $name,
			);
			$id             =   M('file')->add($file_data);
			$data           =   array(
				'url'       =>  $domain.$project.$year_p.$month_p.$day_p.$name,
				'uri'       =>  $project.$year_p.$month_p.$day_p.$name,
				'id'        =>  $id,
			);
			$this->ajaxReturn(array('msg'=>'上传成功','code'=>1,'data'=>$data));
		}else{
			$this->ajaxReturn(array('msg'=>'上传失败','code'=>40000,'data'=>[]));
		}

	}
}